'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18051
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Resources
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyTitle("EveHQ.DataUpgrader"),  _
 Assembly: AssemblyDescription("Eve Online game tool"),  _
 Assembly: AssemblyCompany("Indicium Technologies"),  _
 Assembly: AssemblyProduct("EveHQ"),  _
 Assembly: AssemblyCopyright("� EveHQ Development Team 2005-2013"),  _
 Assembly: AssemblyFileVersion("2.12.3.4222-Beta20130914165508"),  _
 Assembly: AssemblyVersion("2.12.3.4222"),  _
 Assembly: AssemblyConfiguration("Debug"),  _
 Assembly: AssemblyTrademark("2013-09-14 (Version 2.12.3.4222-Beta20130914165508)"),  _
 Assembly: CLSCompliant(false),  _
 Assembly: ComVisible(false),  _
 Assembly: Guid("73dbe256-f27d-4f35-819f-ad46487fffb3")> 

