'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EveHQ.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to attributeID,attributeGroup
        '''9,1
        '''70,1
        '''283,1
        '''265,2
        '''267,2
        '''268,2
        '''269,2
        '''270,2
        '''263,3
        '''479,3
        '''271,3
        '''272,3
        '''273,3
        '''274,3
        '''482,4
        '''55,4
        '''76,5
        '''79,5
        '''192,5
        '''208,5
        '''209,5
        '''210,5
        '''211,5
        '''552,5
        '''564,5
        '''37,6
        '''819,6
        '''820,6
        '''821,6
        '''822,6
        '''182,7
        '''183,7
        '''184,7
        '''277,7
        '''278,7
        '''279,7
        '''11,8
        '''12,8
        '''13,8
        '''14,8
        '''48,8
        '''101,8
        '''102,8
        '''114,9
        '''116,9
        '''117,9
        '''118,9
        '''51,9
        '''64,9
        '''506,9
        '''507,9
        '''54,10
        '''158,10
        '''193,10
        '''247,10
        '''481,11
        '''252,11
        '''562,11
        '''504,12
        '''103,12
        '''105,12
        '''20,12
        '''6,13
        '''30,13
        '''50,13
        '''73,13
        '''180,14
        '''181,14
        '''275,14
        '''.
        '''</summary>
        Friend ReadOnly Property attributeGroups() As String
            Get
                Return ResourceManager.GetString("attributeGroups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to agtAgents, divisionID, crpNPCDivisions, divisionID
        '''agtAgents, corporationID, crpNPCCorporations, corporationID
        '''agtAgents, stationID, staStations, stationID
        '''agtAgents, agentTypeID, agtAgentTypes, agentTypeID
        '''agtConfig, agentID, agtAgents, agentID
        '''chrBloodlines, raceID, chrRaces, raceID
        '''chrBloodlines, shipTypeID, invTypes, typeID
        '''chrBloodlines, corporationID, crpNPCCorporations, corporationID
        '''chrBloodlines, graphicID, eveGraphics, graphicID
        '''chrFactions, solarSystemID, mapSolarSystems, solarSystemID
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DB_Links() As String
            Get
                Return ResourceManager.GetString("DB_Links", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to agtAgents, agentID
        '''AgtAgentTypes, agentTypeID
        '''agtConfig, &lt;none&gt;
        '''chrBloodlines, bloodlineID
        '''chrFactions, factionID
        '''chrRaces, raceID
        '''chrSchools, schoolID
        '''crpNPCCorporationDivisions, &lt;none&gt;
        '''crpNPCCorporations, corporationID
        '''crpNPCDivisions, divisionID
        '''dgmAttributeTypes, attributeID
        '''dgmEffects, effectID
        '''dgmTypeAttributes, &lt;none&gt;
        '''dgmTypeEffects, &lt;none&gt;
        '''eveGraphics, graphicID
        '''eveNames, itemID
        '''eveUnits, unitID
        '''invBlueprintTypes, blueprintTypeID
        '''invCategories, categoryID
        '''invContrabandTypes, &lt;none [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DB_Primary() As String
            Get
                Return ResourceManager.GetString("DB_Primary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE dbo.crtCategories
        '''(
        '''  categoryID   integer,
        '''  description  memo,
        '''  categoryName text(255),
        '''  CONSTRAINT crtCategories_PK PRIMARY KEY (categoryID)
        ''');
        '''
        '''CREATE TABLE dbo.crtClasses
        '''(
        '''  classID      integer,
        '''  description  memo,
        '''  className    text(255),
        '''  CONSTRAINT crtClasses_PK PRIMARY KEY (classID)
        ''');
        '''
        '''CREATE TABLE dbo.crtRelationships
        '''(
        '''  relationshipID    integer,
        '''  parentID          integer,
        '''  parentTypeID      integer,
        '''  parentLevel       integer,
        '''  childID           i [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dbo_TABLES_MDB() As String
            Get
                Return ResourceManager.GetString("dbo_TABLES_MDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- MySQL dump 10.10
        '''--
        '''-- Host: localhost    Database: mssql
        '''-- ------------------------------------------------------
        '''-- Server version	5.0.24a
        '''
        '''/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
        '''/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
        '''/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
        '''/*!40101 SET NAMES utf8 */;
        '''/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
        '''/*!40103 SET TIME_ZONE=&apos;+00:00&apos; */;
        '''/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CH [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dbo_TABLES_MySQL() As String
            Get
                Return ResourceManager.GetString("dbo_TABLES_MySQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE dbo.staOperations
        '''(
        '''  activityID             tinyint         NOT NULL,
        '''  operationID            tinyint         NOT NULL,
        '''  operationName          nvarchar(100)   NOT NULL DEFAULT &apos;&apos;,
        '''  [description]          nvarchar(1000)  NOT NULL DEFAULT &apos;&apos;,
        '''  fringe                 tinyint         NOT NULL DEFAULT 0,
        '''  corridor               tinyint         NOT NULL DEFAULT 0,
        '''  hub                    tinyint         NOT NULL DEFAULT 0,
        '''  border                 tinyint         NOT NULL DEFAULT 0,        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dbo_TABLES_SQL() As String
            Get
                Return ResourceManager.GetString("dbo_TABLES_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to typeID,attributeID,valueInt,valueFloat
        '''1194,6,0,NULL
        '''1194,9,7200,NULL
        '''1194,51,NULL,2500
        '''1194,54,500000,NULL
        '''1194,55,NULL,500000
        '''1194,64,NULL,5
        '''1194,114,16,NULL
        '''1194,116,16,NULL
        '''1194,117,28,NULL
        '''1194,118,28,NULL
        '''1194,154,75000,NULL
        '''1194,158,NULL,50000
        '''1194,160,NULL,0.4
        '''1194,182,3373,NULL
        '''1194,192,8,NULL
        '''1194,193,1,NULL
        '''1194,208,NULL,1000
        '''1194,209,NULL,1000
        '''1194,210,NULL,1000
        '''1194,211,NULL,1000
        '''1194,245,364,NULL
        '''1194,247,1000000,NULL
        '''1194,263,NULL,4800
        '''1194,265,7200,NULL
        '''1194,267,NULL [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EntityData() As String
            Get
                Return ResourceManager.GetString("EntityData", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property EveHQDB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EveHQDB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to typeID,activity,requiredTypeID,quantity,damagePerJob
        '''22,9,34,300,1
        '''22,9,39,166,1
        '''22,9,40,333,1
        '''17455,9,34,269,1
        '''17455,9,35,538,1
        '''17455,9,36,269,1
        '''1223,9,35,170,1
        '''1223,9,39,341,1
        '''1223,9,40,170,1
        '''17466,9,34,735,1
        '''17466,9,35,147,1
        '''17466,9,40,147,1
        '''17470,9,34,1050,1
        '''17463,9,34,875,1
        '''17463,9,35,437,1
        '''17425,9,34,315,1
        '''17425,9,39,174,1
        '''17425,9,40,350,1
        '''1225,9,34,331,1
        '''1225,9,38,331,1
        '''1225,9,39,663,1
        '''17433,9,34,364,1
        '''17433,9,38,364,1
        '''17433,9,39,729,1
        '''1232,9,34,250,1
        '''1232,9,38,500,1
        '''1232,9 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property materialsForRefining() As String
            Get
                Return ResourceManager.GetString("materialsForRefining", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property plugin_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plugin_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to typeID,attributeID,valueInt,valueFloat
        '''30463,1381,null,9
        '''30463,1382,null,3600
        '''30463,1383,null,1000000000
        '''30463,1384,null,50000000
        '''30463,1385,null,150000000
        '''30463,1457,null,0
        '''30579,1381,null,1
        '''30579,1382,null,960
        '''30579,1383,null,100000000
        '''30579,1384,null,20000000
        '''30579,1385,null,20000000
        '''30579,1457,null,296
        '''30583,1381,null,2
        '''30583,1382,null,960
        '''30583,1383,null,350000000
        '''30583,1384,null,70000000
        '''30583,1385,null,160000000
        '''30583,1457,null,297
        '''30584,1381,null,3
        '''30584,1382,null,1440
        '''30584,138 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WHAttribs() As String
            Get
                Return ResourceManager.GetString("WHAttribs", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
