'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18051
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Resources
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyTitle("EveHQ.Prism"),  _
 Assembly: AssemblyDescription("Eve Online game tool"),  _
 Assembly: AssemblyCompany("Indicium Technologies"),  _
 Assembly: AssemblyProduct("EveHQ"),  _
 Assembly: AssemblyCopyright("� EveHQ Development Team 2005-2013"),  _
 Assembly: AssemblyFileVersion("2.12.3.4255-Beta20131002185007"),  _
 Assembly: AssemblyVersion("2.12.3.4255"),  _
 Assembly: AssemblyConfiguration("Debug"),  _
 Assembly: AssemblyTrademark("2013-10-02 (Version 2.12.3.4255-Beta20131002185007)"),  _
 Assembly: CLSCompliant(false),  _
 Assembly: ComVisible(false),  _
 Assembly: Guid("17222945-a308-454a-89ea-a1ce05712ee8")> 

