//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Software Addicts Studios")]
[assembly: AssemblyProduct("EveHQ")]
[assembly: AssemblyCopyright("� EveHQ Development Team 2005-2014")]
[assembly: AssemblyFileVersion("3.0.0.$REVNUM$-Beta-")]
[assembly: AssemblyVersion("3.0.0.$REVNUM$")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyTrademark("$UTCDATE$ (Version 3.0.0.$REVNUM$-Beta-)")]
[assembly: CLSCompliant(false)]
[assembly: ComVisible(false)]


