//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveHQ.PosManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EveHQ.PosManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap anchor {
            get {
                object obj = ResourceManager.GetObject("anchor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap anchor1 {
            get {
                object obj = ResourceManager.GetObject("anchor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap APIUpdate {
            get {
                object obj = ResourceManager.GetObject("APIUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Bounty {
            get {
                object obj = ResourceManager.GetObject("Bounty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Caldari_3232 {
            get {
                object obj = ResourceManager.GetObject("Caldari_3232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Charter {
            get {
                object obj = ResourceManager.GetObject("Charter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CloneBay {
            get {
                object obj = ResourceManager.GetObject("CloneBay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Coolant {
            get {
                object obj = ResourceManager.GetObject("Coolant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DPS {
            get {
                object obj = ResourceManager.GetObject("DPS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EHP {
            get {
                object obj = ResourceManager.GetObject("EHP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap enrUran {
            get {
                object obj = ResourceManager.GetObject("enrUran", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Fitting {
            get {
                object obj = ResourceManager.GetObject("Fitting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fuel_cost {
            get {
                object obj = ResourceManager.GetObject("fuel_cost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fuel_stront_cost {
            get {
                object obj = ResourceManager.GetObject("fuel_stront_cost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FuelStrontium {
            get {
                object obj = ResourceManager.GetObject("FuelStrontium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap H2Iso {
            get {
                object obj = ResourceManager.GetObject("H2Iso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HeIso {
            get {
                object obj = ResourceManager.GetObject("HeIso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HvyWater {
            get {
                object obj = ResourceManager.GetObject("HvyWater", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon02_07 {
            get {
                object obj = ResourceManager.GetObject("icon02_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon02_12 {
            get {
                object obj = ResourceManager.GetObject("icon02_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon03_13 {
            get {
                object obj = ResourceManager.GetObject("icon03_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon03_131 {
            get {
                object obj = ResourceManager.GetObject("icon03_131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon04_12 {
            get {
                object obj = ResourceManager.GetObject("icon04_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon07_12 {
            get {
                object obj = ResourceManager.GetObject("icon07_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon09_09 {
            get {
                object obj = ResourceManager.GetObject("icon09_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon10_10 {
            get {
                object obj = ResourceManager.GetObject("icon10_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon12_07 {
            get {
                object obj = ResourceManager.GetObject("icon12_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon17_04 {
            get {
                object obj = ResourceManager.GetObject("icon17_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon22_06 {
            get {
                object obj = ResourceManager.GetObject("icon22_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon22_07 {
            get {
                object obj = ResourceManager.GetObject("icon22_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon22_17 {
            get {
                object obj = ResourceManager.GetObject("icon22_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon22_18 {
            get {
                object obj = ResourceManager.GetObject("icon22_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon22_19 {
            get {
                object obj = ResourceManager.GetObject("icon22_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon22_20 {
            get {
                object obj = ResourceManager.GetObject("icon22_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Insure {
            get {
                object obj = ResourceManager.GetObject("Insure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Isotope {
            get {
                object obj = ResourceManager.GetObject("Isotope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LiqOzone {
            get {
                object obj = ResourceManager.GetObject("LiqOzone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MechParts {
            get {
                object obj = ResourceManager.GetObject("MechParts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NitgIso {
            get {
                object obj = ResourceManager.GetObject("NitgIso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap noitem {
            get {
                object obj = ResourceManager.GetObject("noitem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Offline_btn {
            get {
                object obj = ResourceManager.GetObject("Offline_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap online {
            get {
                object obj = ResourceManager.GetObject("online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap online_anchor {
            get {
                object obj = ResourceManager.GetObject("online_anchor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap online_btn {
            get {
                object obj = ResourceManager.GetObject("online_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap online1 {
            get {
                object obj = ResourceManager.GetObject("online1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OxIso {
            get {
                object obj = ResourceManager.GetObject("OxIso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Oxygen {
            get {
                object obj = ResourceManager.GetObject("Oxygen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap plugin_icon {
            get {
                object obj = ResourceManager.GetObject("plugin_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PosShield {
            get {
                object obj = ResourceManager.GetObject("PosShield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Reinforce_btn {
            get {
                object obj = ResourceManager.GetObject("Reinforce_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Repair {
            get {
                object obj = ResourceManager.GetObject("Repair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Robotics {
            get {
                object obj = ResourceManager.GetObject("Robotics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Shield {
            get {
                object obj = ResourceManager.GetObject("Shield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ShieldCharge {
            get {
                object obj = ResourceManager.GetObject("ShieldCharge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Strontium {
            get {
                object obj = ResourceManager.GetObject("Strontium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap un_anchor {
            get {
                object obj = ResourceManager.GetObject("un_anchor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap un_anchor1 {
            get {
                object obj = ResourceManager.GetObject("un_anchor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
